### ISSUE TITLE
there is some problem with bestn.pt

### ISSUE THREAD

**Issue by anuragsurve** [samay-jain/Advanced-Automatic-Number-Plate-Recognition-System-ANPR-#3]
Error executing job with overrides: ['model=bestn.pt', 'source=test video.mp4']
Traceback (most recent call last):
  File "/home/frostfire/anprtrial/Advanced-Automatic-Number-Plate-Recognition-System-ANPR--main/predict.py", line 149, in predict
    predictor()
  File "/home/frostfire/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/frostfire/anprtrial/Advanced-Automatic-Number-Plate-Recognition-System-ANPR--main/ultralytics/yolo/engine/predictor.py", line 164, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "/home/frostfire/anprtrial/Advanced-Automatic-Number-Plate-Recognition-System-ANPR--main/ultralytics/yolo/engine/predictor.py", line 121, in setup
    model = AutoBackend(model, device=device, dnn=self.args.dnn, fp16=self.args.half)
  File "/home/frostfire/anprtrial/Advanced-Automatic-Number-Plate-Recognition-System-ANPR--main/ultralytics/nn/autobackend.py", line 73, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/home/frostfire/anprtrial/Advanced-Automatic-Number-Plate-Recognition-System-ANPR--main/ultralytics/nn/tasks.py", line 303, in attempt_load_weights
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
  File "/home/frostfire/.local/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/frostfire/.local/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/frostfire/.local/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'bestn.pt'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by samay-jain** [comment]
please move the weight 'bestn.pt' in the same directory and also remove the space you entered in 'source=test video.mp4'. kindly try once again without entering space in the name of video file like 'source=test_video.mp4' or rename it.

**Comment by anuragsurve** [comment]
its not getting downloaded so got it from other repo. It started working now. Only problem is its not detecting square number plate.
